### ISSUE TITLE
RE: The Recent Updates/Seth

### ISSUE THREAD

**Issue by silver2row** [MomsFriendlyRobotCompany/tfmini#2]
Hello,

Seth here. I was trying to configure things from this lib. to handle python3. I have failed so far. I am missing something. But in the meantime, you guys or just you finalized the issue and fixed everything. 

I will test it soon. If there are any updates that need attention outside of what you have done, please let me know.

Seth

P.S. I can try to configure things again. Off to test soon! You are a life saver for giving out this knowledge. I am aware of the license too. Thank you!

**Comment by silver2row** [comment]
Hello Again,

I use, to this day, the pysabertooth lib. you produced. Also, w/ tfmini for python3, I noticed some of the changes in tfmini.py. 

...

One thing that caught my eye was the `/dev/ttyUSB1234` and the other two port options. 

Is there a way to use this lib. w/ a UART connection, i.e. say /dev/ttyS2?

Seth

**Comment by walchko** [comment]
Hello!

The port /dev/ttyUSB1234 is just an example port name … it isn’t real. I do my development on macOS and Linux (Ubuntu and Raspberry Pi) and they all handle serial port naming differently. Please note, a UART and serial port are the same thing, it just depends if it is the hardware serial port on say a Raspberry Pi (or other computer) or some USB UART you can buy from Adafruit or Sparkfun. The OS just names them differently, but you interact with them the same.

**Comment by silver2row** [comment]
Hello...yes sir. I understand...I use a beaglebone black and other boards from their organization. I have been able to use some of your libs. so far on that specific family of boards.

...

/dev/ttyS2 or whatever...

Got it. Thank you.

Seth

P.S. I usually use Debian or Windows. But for Win 10, I use PuTTY to handle the BBB and their family of boards. Anyway, thank you for making me better understand it all. I will test again!

**Comment by silver2row** [comment]
Hello,

I am still receiving the error:

    debian@beaglebone:~/Morty$ ./TF.py
    =========================
    Traceback (most recent call last):
      File "./TF.py", line 12, in <module>
        d = tf.read()
      File "/home/debian/.local/lib/python3.7/site-packages/tfmini/tfmini.py", line 123, in read
        if ret > 12.0 or ret < 0.3:
    TypeError: '>' not supported between instances of 'NoneType' and 'float'

...

Please send any advice.

Seth

**Comment by walchko** [comment]
sorry for the delay ... made some updates, it should work now

**Comment by silver2row** [comment]
Hello Sir,

Thank you. I tried by making the float and other float ints but that did not pan out well enough.

Seth

P.S. I will test it soon to report back. Thank you again for making a library for this small sensor.

**Comment by silver2row** [comment]
Hello Sir,

I am lost now. I saw the updates and the "correct" way of achieving the fix of the error I was receiving. I am now receiving all sorts of errors.

Seth

P.S. I will recreate the issue and report back.

**Comment by walchko** [comment]
did you try my example? This is what I used to test it with ... just change the port to what is correct for you.

```python
#!/usr/bin/env python3
#
# MIT License
#

import time
from tfmini import TFmini

port = "/dev/tty.usbserial-A904MISU"

# mode = TFmini.PIX_MODE # Pixhawk - ascii
mode = TFmini.STD_MODE # packet

tf = TFmini(port, mode=mode)

try:
    print('='*25)
    # while True:
    for _ in range(100):
        d = tf.read()
        if d:
            print(f'Distance: {d:5}')
        else:
            print('No valid response')
        time.sleep(0.01)

except KeyboardInterrupt:
    tf.close()
    print('bye!!')
```

**Comment by walchko** [comment]
If you still have problems ... you can also try [adafruit-circuitpython-tfmini](https://pypi.org/project/adafruit-circuitpython-tfmini/). I haven't used it, but they are a very respectable company and do good work! 😄

**Comment by silver2row** [comment]
Hello,

Thank you for the quick reply. 

```

Traceback (most recent call last):
  File "./FirstLiDar.py", line 13, in <module>
    tf = TFmini('/dev/ttyS2')
  File "/home/debian/.local/lib/python3.7/site-packages/tfmini/tfmini.py", line 222, in __init__
    self.proto = Pix(port)
  File "/home/debian/.local/lib/python3.7/site-packages/tfmini/tfmini.py", line 169, in __init__
    self.format(cmd)
  File "/home/debian/.local/lib/python3.7/site-packages/tfmini/tfmini.py", line 39, in format
    self.__config(newmode)
  File "/home/debian/.local/lib/python3.7/site-packages/tfmini/tfmini.py", line 94, in __config
    if self.__sendRespond(ENTER):
  File "/home/debian/.local/lib/python3.7/site-packages/tfmini/tfmini.py", line 79, in __sendRespond
    if reply[2] == 0x01:
TypeError: 'NoneType' object is not subscriptable

```

Here is what happens when I run that exact example w/ the: ` port = "/dev/ttyS2" ` .

Seth

P.S. I will keep trying. Sorry for keeping my complaints current.
